spring.application.name=debtmanager
spring.profiles.active=local

# General JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Server
server.shutdown=graceful
server.port=8080
